name: medcare
description: A full health app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/appointment.png
    - assets/doctor.png
    - assets/doctor2.png
    - assets/doctor3.png
    - assets/hospital.png
    - assets/virus.png